### ISSUE TITLE
Agenda: Governance meeting June 23 2019

### ISSUE THREAD

**Issue by 0xSSoul** [carboclan/pm#1]
Solicit suggestions for agenda items for the Governance meeting to be held on June 23th 2:00 (UTC) online. Please comment to provide topics or suggestions.

# Proposed agenda
1. Community's mission
2. Organization principle
3. Hashrate project goal
4. Ecnomics model of hashrate projects
5. Reconciliate existing work
6. Roadmap

**Comment by 0xSSoul** [comment]
### 使命
在之前会议的基础上，提出社区的使命： 让天下没有难挖的矿

### 社区的组织原则
这是一个开放的社区，任何人只要认同社区使命都可以加入社区贡献力量。社区是非盈利性的，社区及社区成员都可以接受捐赠，但不接受任何以商业回报为目的的投资。在社区使命下，社区将发起若干项目。这些项目将有独立的经济模型，因项目需要也可以接受公平的商业投资。社区成员可以以个人名义投资这些项目。社区负责审核项目的投资人资质。社区是高度独立的，社区不对投资人负责也不对投资人做任何承诺。社区可以接受来自项目收益的捐赠以持续发展。

### 算力衍生品项目
算力衍生品项目是社区的第一批项目之一。算力衍生品项目的目标是：剥离挖矿风险，让投资挖矿的资金和风险相匹配，让挖矿市场更有效。

### 算力衍生品项目的经济模式

算力衍生品项目在运营过程中的需要三类资源：
1. 流动性提供方。包括矿工、矿场、矿机厂商、区块链资管团队、交易所、OTC Broker 等等。流动性提供方的贡献度是以成交量衡量的，很难在初期确定资源方的贡献度。
2. 用于强行平仓兜底的资金。
3. 向社区捐赠用于后续发展的资金。

算力衍生品项目可能的商业收益来源：
1. 交易手续费，与之相关的是第一类资源。
2. 强行平仓罚金，与之相关的是第二类资源。

总体上，有两种分配收益的经济模式
1. 集中化的类股权方式。
流动性提供方也作为兜底资金提供方也作为捐赠资金提供方。由流动性提供方公平认购股权（或股权币），认购资金进入资金池用于强行平仓兜底和向社区捐赠。项目的收益不直接分配给股权投资人，而是进入资金池。
股权模式下，平台的核心参数（保证金比例、罚金比例等）由股权投资人决定。

2. 分散的方式。
分散方式没有类似股权的机制。交易手续费的全部或部分分配给提供流动性的资源方，类似销售渠道。任何人都可以对保证金不足的合约进行兜底，并获取强行平仓罚金。社区可以从上述收益中强行划分一定比例用于后续发展，也可以不设置硬性比例而是由收益人主动捐赠。
分散模式下，平台的核心参数（保证金比例、罚金比例等）由社区决定。

需要对上述经济模型进行讨论

### 算力衍生品的早期交易模式
OTC还是集合竞价。需要考虑流动性特点和技术上的难度。可以从OTC做起来，现在的UX应该也有大量可以直接用。

-------

### Mission

Based on the previous meeting, the mission of the community: Let mining easy? (How to translate?)

### Community Organization Principle
This is an open community where anyone who recognize the community's mission is allowed to join the community. Communities are not-for-profit, while both the community itself and the community members can accept donations. However, the community do not accept any investment for commercial returns. Under the community’s mission, the community will launch several projects. These projects will have independent economic models and can accept fair commercial investment as the project needs. Community members can invest in these projects on their own behalf. The community is responsible for reviewing the investor qualifications of the project. The community is highly independent, and the community is not accountable to investors and does not make any commitment to investors. The community can accept donations from project revenues for continued growth.

### Hashrate Derivatives Project
The Hashrate Derivatives Project is one of the first projects in the community. The goal of the Hashrate Derivatives Project is to divest mining risks, make the mining funds match the risks and make the mining market more effective.

### Economic model of the hashrate derivatives project
The Hashrate derivatives project needs three types of resources in the operation process:
1. Liquidity provider. Including miners, mining machine manufacturers, block chain investment management team, exchanges, OTC Broker and so on. The contribution of the liquidity provider is measured by the volume of the transaction, and it is difficult to determine the contribution of the resource side at an early stage.
2. The funds used to forcibly close the position.
3. Donate funds to the community for follow-up development.

Possible sources of business income for the Hashrate Derivatives Project:
1. The transaction fee, which is related to the first type of resources.
2. The forced liquidation penalty, which is related to the second type of resources.

In general, there are two economic models for distributing income.

1. Centralized equity-like approach.
The liquidity provider also acts as a provider of funds and as a provider of donation funds. The liquidity provider subscribes for equity (or equity token), and the subscription funds enter the pool of funds for forced liquidation and donation to the community. The proceeds of the project are not directly allocated to equity investors, but instead enter the pool of funds.
Under this model, the key parameters of the platform (margin ratio, fine ratio, etc.) are determined by the equity investor.

2. Dispersion approach.
There is no similar equity mechanism in this way. All or part of the transaction fee is allocated to the party providing liquidity, similar to the sales channel. Anyone can buy the position without sufficient margin and get a forced closing penalty. The community can forcibly divide a certain proportion from the above-mentioned income for subsequent development, or it can be donated by the beneficiary without setting a hard proportion.
In this mode, the key parameters of the platform (margin ratio, penalty ratio, etc.) are determined by the community.

Need to discuss the above economic model

### Early trading model of hashrate derivatives
OTC or Set bidding. Need to consider the characteristics of liquidity and technical difficulties. It can be done from OTC, and now there is a good UX that can be used directly.

**Comment by CarboClanC** [comment]
Two additional topics: 1. how do we reconciliate existing work done on Hashedge which is already in engineering phase with the current version on Hashrate derivatives which is still in research phase? 2.We need to come up with a feasible roadmap.
