### ISSUE TITLE
Agenda: Governance meeting July 7th 2019

### ISSUE THREAD

**Issue by 0xSSoul** [carboclan/pm#13]
Solicit suggestions for agenda items for the Governance meeting to be held on July 7th 2:00 (UTC) online. Please comment to provide topics or suggestions.

# Proposed agenda
1. Organizational form of our community
2. Index of contract #9 
3. Naming #17 
4. Physical system time #19

**Comment by CarboClanC** [comment]
# Proposed Agenda

## 1. White Paper Draft remaining items:
### 1.1 Index Design & Contract Specs 
1.1.1 Synthetic POW Mining Index Calculation #9 
1.1.2 Use Block Height vs. Trading Days for Expiration #19 
1.1.3 Trade off between Index Unit & Contract Size #20 
1.1.4 Naming Poll: Index name , Contract name and Abbreviations #17 
### 1.2 Trading Related
1.2.1 Variable Margin on top of Market Protocol - How to collaborate with DyDx or DDex #10 
1.2.2 Walk through example of real world use case as a reality check for Index and Contract design  #21 
### 1.3 Community Projects
1.3.1 Product & Go-to-Market #22 
1.3.2 Community Product Portfolio: Hashrate Insurance, Staking Derivatives, Cloud Mining Contracts etc. #23 

## 2. Governance:
### 2.1 Overview of GNU/Linux and [Apache Software Foundation](http://ocselected.org/posts/foundation_introduce/how_apache_works/)
### 2.2 Proposal of "Yellow Hat DAO" - to build an efficient capital market for blockchain infrastructure
### 2.3 Github usage for collaboration & other administrative matters
