### ISSUE TITLE
Trade off between Index Unit and Contract Size

### ISSUE THREAD

**Issue by CarboClanC** [carboclan/pm#20]
Problem: 
Index at integer number (as designed now) would imply value of the long or short token to be huge. 

Given BTC Mining Index (BMI): hashrate unit **10^18 hashes/second (1 EH/s, or 1 mn TH/s)**

Current Index = BTC 444
Assume:  Cap = BTC 500; Floor = BTC 400
Issuer (Minter) locks up 100WBTC (USD 1.1 mn) to mint 1 pair of Long & Short Tokens.
1 Long token value = 44 WBTC (USD 0.50mn)
1 Short token value = 56 WBTC (USD 0.64mn) 

Typically for cloud mining contracts, the average order size varies from 50 USD to 50,000 USD. Order size of cloud mining contracts on BitDeer (Bitmain) goes from 20-10,000 T/s.

This would imply,  retail investors would likely purchase  **0.0001 - 0.1 long/short token per contract order**.

Alternatives:

(1) Given BTC Mining Index (BMI): hashrate unit  **10^12 h/s (1 TH/s)**

Current Index = BTC 0.000444
Assume:  Cap = BTC 0.000500; Floor = BTC 0.000400
Issuer (Minter) locks up 0.0001 WBTC (USD 1.1) to mint 1 pair of Long & Short Tokens.
1 Long token value = 0.000044 WBTC (USD 0.50)
1 Short token value = 0.000056 WBTC (USD 0.64) 
Retail Investors likely purchase **100 - 100,000 tokens per contract order**.

(2) Given BTC Mining Index (BMI): hashrate unit **10^15 h/s (1 PH/s, or 1,000 TH/s)**

Current Index = BTC 0.444
Assume: Cap =  BTC 0.500; Floor = BTC 0.400
Issuer (Minter) locks up 0.1 WBTC (USD 1,100) to mint 1 pair of Long & Short Tokens
1 Long token value = 0.044 WBTC (USD 503)
1 Short token value = 0.056 WBTC (USD 640)
Retail Investors likely purchase **0.1 - 99 tokens per contract order**.

**Comment by tzhan28** [comment]
Problem:
Index at integer number (as designed now) would imply value of the long or short token to be huge.
Given ETH Mining Index (EMI): hashrate unit 10^12 hashes/second (1 TH/s, )
Current Index = ETH 84
Assume: Cap = BTC 70; Floor = BTC 100
Issuer (Minter) locks up 30 WETH (USD 8800 usd) to mint 1 pair of Long & Short Tokens.
1 Long token value = 14 WETH (USD 4100)
1 Short token value =16 WETH (USD 4700)
Typically for cloud mining contracts, the average order size varies from 50 USD to 50,000 USD. Order size of cloud mining contracts on BitDeer (Bitmain) goes from 20-10,000 T/s.
This would imply, retail investors would likely purchase 0.01-10 long/short token per contract order.

Alternatives:
(1) Given ETH Mining Index (EMI): hashrate unit 10^9 h/s (1 GH/s)
Current Index = ETH 0.084
Assume: Cap = ETH 0.1; Floor = ETH 0.07
Issuer (Minter) locks up 0.03 WETH (USD 8.8) to mint 1 pair of Long & Short Tokens.
1 Long token value = 0.014 WETH (USD 4.1)
1 Short token value = 0.016 WETH (USD 4.7)
Retail Investors likely purchase 10 - 10,000 tokens per contract order.

**Comment by tzhan28** [comment]
The index number I have for BTC, when using hashrate unit 10^18 hashes/second (1 EH/s, or 1 mn TH/s), is at 34 not 444. So it should be about 10 times smaller

**Comment by tzhan28** [comment]
Having a coefficient for index calculation should be fine. Lots of indexes started at an arbitrary round number like 1000, and started from there. 


In our cases, we could keep our indexes number floating in 3 or 4 digits or roughly with in a range where people are accustomed to. On the other hand, we could simply state an multiplication coefficient on the side, (i.e. 10^6 etc)

**Comment by 0xSSoul** [comment]
As proposed at the [candidate 4 of index formula issue](https://github.com/carboclan/pm/issues/9#issuecomment-509917371) , I suppose to use an Index with one digit in integer part and use a contract size to make one position token values at the order of $10.

**Comment by 0xSSoul** [comment]
The contract in [candidate 5 of index](https://github.com/carboclan/pm/issues/9#issuecomment-509917371) is accepted by governance meeting July 14th 2019.
