### ISSUE TITLE
Agenda: Governance meeting July 3th 2019

### ISSUE THREAD

**Issue by 0xSSoul** [carboclan/pm#7]
Solicit suggestions for agenda items for the Governance meeting to be held on July 3th 14:00 (UTC) online. Please comment to provide topics or suggestions.

# Proposed agenda
1. Mission of our community #8 
2. Organizational form of our community
3. Hashrate contract index #9

**Comment by 0xSSoul** [comment]
1. Mission of our community #8

**Comment by Mikefotiaoqing** [comment]
2社区的组织方式

**Comment by CarboClanC** [comment]
4. Product Positioning
